### ISSUE TITLE
Requesting parking spot fails

### ISSUE THREAD

**Issue by ddxic** [simonrupf/parkon-python-client#1]
**The command line return the following error:**
_Error decoding the JSON response of the parking spot request: Expecting value_

The id_request on line 36 doesn't get a JSON response.

**Raw response:**
Portal wurde nicht gefunden.
An error has occurred. This application may no longer respond until reloaded.
Ein Verbindungsfehler ist aufgetreten. Bitte Seite neu laden.

**Comment by simonrupf** [comment]
Unfortunately Parkon has switched their server to using the [Blazor framework](https://learn.microsoft.com/en-us/aspnet/core/blazor/), which uses a websocket for communicating binary messages and have disabled their JSON REST API.

I've not found any python libraries that can communicate with a Blazor server, so I see no way of supporting this client with their current API and have to abandon this project. *sigh* Thank you Microsoft, for supporting open web standards.
